In [ ]:
import pandas as pd

In [ ]:
df_riesgos = pd.read_excel('datos_seleccionados_modelo.xlsx', index_col=0)

In [ ]:
df_riesgos

sectorEmpresa  ixRiesgo  ixPuesto  Incongruencia
181657      0. Otros         1         6              1
181658      0. Otros         1         6              1
...              ...       ...       ...            ...
80479   9. Servicios        47         1              1
80510   9. Servicios        47         1              1

[252857 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(sparse=False)

In [ ]:
ohe_data = ohe.fit_transform(df_riesgos[['sectorEmpresa', 'ixRiesgo', 'ixPuesto']])

In [ ]:
cols = ohe.get_feature_names_out()

In [ ]:
X = pd.DataFrame(ohe_data, columns=cols)

In [ ]:
y = df_riesgos.Incongruencia

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

import tensorflow as tf

In [ ]:
model = tf.keras.Sequential([
  # feature_layer,
  Dense(128, activation='relu'),
  Dense(128, activation='relu'),
  Dropout(.1),
  Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(X, y, epochs=5, batch_size=128)

Epoch 1/5


/Users/sota/miniforge3/envs/deep_learning/lib/python3.10/site-packages/keras/backend.py:5673: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Sigmoid activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(
2023-02-09 21:22:26.440875: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1976/1976 [==============================] - 12s 6ms/step - loss: 0.0519 - accuracy: 0.9847
Epoch 2/5
1976/1976 [==============================] - 11s 6ms/step - loss: 0.0217 - accuracy: 0.9935
Epoch 3/5
1976/1976 [==============================] - 12s 6ms/step - loss: 0.0200 - accuracy: 0.9938
Epoch 4/5
1976/1976 [==============================] - 11s 6ms/step - loss: 0.0193 - accuracy: 0.9939
Epoch 5/5
1976/1976 [==============================] - 11s 6ms/step - loss: 0.0189 - accuracy: 0.9939


In [ ]:
df_to_pred = pd.DataFrame({
    'sectorEmpresa': '1. Construcción',
    'ixRiesgo': 1,
    'ixPuesto': 7
}, index=[0])

In [ ]:
df_to_pred

sectorEmpresa  ixRiesgo  ixPuesto
0  1. Construcción         1         7

In [ ]:
X_to_pred = ohe.transform(df_to_pred)

In [ ]:
model.predict(X_to_pred)

1/1 [==============================] - 0s 68ms/step


2023-02-09 21:27:18.338484: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


array([[0.00271205]], dtype=float32)

In [ ]:
df_riesgos.query('Incongruencia == 1 & sectorEmpresa == "1. Construcción"')

sectorEmpresa  ixRiesgo  ixPuesto  Incongruencia
242658  1. Construcción         1         2              1
242881  1. Construcción       261         1              1
...                 ...       ...       ...            ...
251189  1. Construcción       260         6              1
251190  1. Construcción       260         6              1

[1769 rows x 4 columns]

In [ ]:
df_to_pred = pd.DataFrame({
    'sectorEmpresa': '1. Construcción',
    'ixRiesgo': 1,
    'ixPuesto': 2
}, index=[0])

In [ ]:
df_to_pred

sectorEmpresa  ixRiesgo  ixPuesto
0  1. Construcción         1         2

In [ ]:
X_to_pred = ohe.transform(df_to_pred)

In [ ]:
model.predict(X_to_pred)

1/1 [==============================] - 0s 17ms/step


array([[0.07982568]], dtype=float32)

In [ ]:
df_to_pred = pd.DataFrame({
    'sectorEmpresa': '1. Construcción',
    'ixRiesgo': 261,
    'ixPuesto': 2
}, index=[0])

In [ ]:
df_to_pred

sectorEmpresa  ixRiesgo  ixPuesto
0  1. Construcción       261         2

In [ ]:
X_to_pred = ohe.transform(df_to_pred)

In [ ]:
model.predict(X_to_pred)

1/1 [==============================] - 0s 16ms/step


array([[0.9900108]], dtype=float32)